name: QCNet
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cachecontrol=0.12.14=pyhd8ed1ab_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.3.15=pyhd8ed1ab_0
  - cryptography=39.0.1=py38h9ce1e76_2
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - dateutils=0.6.12=py_0
  - dbus=1.13.0=h4e0c4b3_1000
  - deepdiff=6.2.2=pyhd8ed1ab_0
  - distlib=0.3.6=pyhd8ed1ab_0
  - dulwich=0.21.3=py38h5eee18b_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fastapi=0.88.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.20.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - grpcio=1.48.2=py38he1ff14a_1
  - h11=0.14.0=pyhd8ed1ab_0
  - html5lib=1.1=pyh9f0ad1d_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib_metadata=6.7.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.2.0=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - keyring=23.13.1=py38h578d9bd_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lightning=2.0.3=pyhd8ed1ab_0
  - lightning-cloud=0.5.36=pyhd8ed1ab_0
  - lightning-utilities=0.8.0=pyhd8ed1ab_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - msgpack-python=1.0.3=py38h43d8883_1
  - multidict=6.0.2=py38h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.0=py38h06a4308_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.1.2=py38h06a4308_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - poetry=1.4.2=linux_pyhd8ed1ab_0
  - poetry-core=1.5.2=pyhd8ed1ab_0
  - poetry-plugin-export=1.3.1=pyhd8ed1ab_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - protobuf=3.20.3=py38h6a678d5_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.9.1=py38h0a891b7_0
  - pyg=2.3.0=py38_torch_2.0.0_cu118
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=2.0.1=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cluster=1.6.1=py38_torch_2.0.0_cu118
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.0.4=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.1=py38_torch_2.0.0_cu118
  - pytorch-sparse=0.6.17=py38_torch_2.0.0_cu118
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - rapidfuzz=2.13.7=py38h417a72b_0
  - re2=2022.04.01=h27087fc_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py38h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rich=13.4.2=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py38h6a678d5_1
  - scipy=1.10.1=py38hf6e8229_1
  - secretstorage=3.3.3=py38h578d9bd_1
  - setuptools=67.8.0=py38h06a4308_0
  - shellingham=1.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.22.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.11.1=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - torchaudio=2.0.2=py38_cu118
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu118
  - tqdm=4.65.0=py38hb070fc8_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.5.24=pyhd8ed1ab_0
  - typing-extensions=4.6.3=py38h06a4308_0
  - typing_extensions=4.6.3=py38h06a4308_0
  - urllib3=1.26.16=py38h06a4308_0
  - uvicorn=0.22.0=py38h578d9bd_0
  - virtualenv=20.21.1=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.0=pyhd8ed1ab_0
  - websockets=10.3=py38h0a891b7_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
